modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fontswitcher"
version = "${version}"
displayName = "Font Switcher"
authors = "Mysticpasta1, Waterpicker"
description = '''
Switch to a modded font from your mod's resource folder
'''
#logoFile = ""

[[dependencies.fontswitcher]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fontswitcher]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fontswitcher]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"